packages/wallets/src/coin98/coin98.page.ts, packages/wallets/src/mathwallet/mathwallet.page.ts, packages/wallets/src/metamask/metamask.page.ts, packages/wallets/src/wallet.page.ts, packages/widgets/src/ethereum/ethereum.constants.ts, packages/widgets/src/index.ts, packages/widgets/src/kusama/index.ts, packages/widgets/src/kusama/kusama.constants.ts, packages/widgets/src/kusama/kusama.page.ts, packages/widgets/src/polygon/polygon.constants.ts, packages/widgets/src/widgets.constants.ts, wallets-testing/browser/browser.constants.ts, wallets-testing/browser/browser.service.ts, wallets-testing/test/widgets/kusama.spec.ts
Added kusama connection to https://kusama.lido.fi/ on mainnet
=> Kusama test init

packages/widgets/src/index.ts, packages/widgets/src/polkadot/index.ts, packages/widgets/src/polkadot/polkadot.constants.ts, packages/widgets/src/polkadot/polkadot.page.ts, wallets-testing/browser/browser.constants.ts, wallets-testing/test/widgets/polkadot.spec.ts
Added polkadot connection to https://polkadot.lido.fi/ via Metamask
=> Polkadot init

packages/wallets/src/coin98/coin98.page.ts, packages/wallets/src/coinbase/coinbase.page.ts, packages/wallets/src/exodus/exodus.page.ts, packages/wallets/src/gamestop/gamestop.page.ts, packages/wallets/src/index.ts, packages/wallets/src/mathwallet/mathwallet.page.ts, packages/wallets/src/metamask/metamask.page.ts, packages/wallets/src/phantom/phantom.page.ts, packages/wallets/src/tally/tally.page.ts, packages/wallets/src/trustwallet/trustWalletPage.ts, packages/wallets/src/trustwallet/trustwallet.constants.ts, packages/wallets/src/xdefi/index.ts, packages/wallets/src/xdefi/xdefi.constants.ts, packages/wallets/src/xdefi/xdefi.page.ts, packages/widgets/src/ethereum/ethereum.page.ts, wallets-testing/browser/browser.constants.ts, wallets-testing/test/widgets/ethereum.spec.ts
- added xdefi connection test to eth widget
- delete unused pop-up close since it`s this banner removed from eth widget("Go to 1inch when rate >1.05)
- delete all closePopover from wallets pages since was misunderstanding of it 
- refactor navigation method to use EXTENSION_START_PATH from wallets constants
=> Wallets update

packages/wallets/src/xdefi/xdefi.page.ts
1)Fixed locators
2)added  waitForSelector for XDEFI firsTime flag in due to long load of page elements in DOM. It was lead to skip extension setup function and browser have tried to open widget with skipped extension setup step.
=> Xdefi update

.github/workflows/deploy.yml, package.json
=> Use yarn scripts to publish

packages/wallets/src/index.ts, packages/wallets/src/taho/index.ts, packages/wallets/src/taho/taho.constants.ts, packages/wallets/src/taho/taho.page.ts, packages/wallets/src/tally/index.ts, packages/wallets/src/trustwallet/trustWalletPage.ts, wallets-testing/browser/browser.constants.ts, wallets-testing/playwright.config.ts, wallets-testing/test/widgets/ethereum.spec.ts
=> Wallets updates

packages/wallets/src/metamask/metamask.page.ts, packages/wallets/src/wallet.page.ts, packages/widgets/src/polygon/polygon.page.ts
Metamask added double check the approve operation.
Added steps for double check approve tx.
=> Polygon fix

wallets-testing/playwright.config.ts
=> Attach screenshots and traces

packages/wallets/src/metamask/metamask.page.ts
Metamask have added terms-privacy checkbox at the onboarding page
=> add terms checkbox action

packages/wallets/src/exodus/exodus.page.ts
Exodus have added password setup during extension setup.
Added setup password steps into Exodus firstTimeSetup()
=> Exodus fix

packages/wallets/src/exodus/exodus.page.ts
exodus have added the password auth
=> fix: exodus password auth and connect timeout

wallets-testing/test/widgets/ethereum.spec.ts, wallets-testing/test/widgets/polygon.spec.ts, wallets-testing/test/widgets/solana.spec.ts
Skip exodus since flaky weird bug.
=> skip exodus

packages/wallets/src/coinbase/coinbase.page.ts
Coinbase: Added one more step for seed recovery to be done
=> fix: add step to confirm seed recovery for coinbase

wallets-testing/test/widgets/ethereum.spec.ts
Skip MM stake test since won't fix for now
=> skip MM stake test

packages/wallets/src/index.ts, packages/wallets/src/okx/index.ts, packages/wallets/src/okx/okx.constants.ts, packages/wallets/src/okx/okx.page.ts, wallets-testing/browser/browser.constants.ts, wallets-testing/test/widgets/ethereum.spec.ts, wallets-testing/test/widgets/polygon.spec.ts
Added OKX wallet connect test to Polygon and Ethereum
=> OKX wallet connect test init

packages/wallets/src/okx/okx.page.ts
- Fixed flaky okx test. Looks like some wallets need for some wait since tests are very fast
=> OKX update

wallets-testing/test/widgets/ethereum.spec.ts, wallets-testing/test/widgets/polygon.spec.ts
Skip okx since it`s very flaky. Need to investigate on which side it`s occurs.
=> fix: skip okx

packages/wallets/src/bitget/bitgetPage.ts
-  fix locator for password fields since after bitGet update the DOM was changed
=> bitGet update

packages/widgets/src/ethereum/ethereum.page.ts
-fix eth widget locators after widget update
=> Update eth widget

packages/wallets/src/coin98/coin98.constants.ts
- fix coin98 nav firstTime route
=> fix: coin98-nav

packages/wallets/src/metamask/metamask.page.ts, packages/wallets/src/wallet.page.ts
- add reject tx function MM.
[Tets npm token publish]
=> feat: add tx reject MM

wallets-testing/test/widgets/solana.spec.ts
- Skip tests for solana widget,since it's sunset and terminate
=> Solana widget sunset

packages/widgets/src/polygon/polygon.page.ts
- added timeout for load data on widget after fork mainnet
=>  possible fix for polygon timeout exceed

.github/workflows/publish.yml
- test dispatched workflow for publish
=> chore: add publish dispatch

.github/workflows/publish.yml
=> feat: revert public dispatch

packages/wallets/src/metamask/metamask.page.ts
=> feat: test feat for release

packages/wallets/src/metamask/metamask.page.ts
- fix locator for walletAddress
=> fix: wallet address locator

packages/wallets/src/okx/okx.page.ts
=> Fix okx seed setup

packages/wallets/src/metamask/metamask.page.ts
- increase resolve time for popover to be visible
=> fix: up resolve time for mm popover

packages/wallets/src/xdefi/xdefi.page.ts
- update XDEFI wallet connection function
=> xdefi connection update

packages/widgets/src/ethereum/ethereum.page.ts, wallets-testing/playwright.config.ts
- increased test timeout (4 min)
- fixed the doStaking function
=> fix-mm-stake

packages/wallets/src/metamask/metamask.page.ts
- update confirm button locator
=> Update the  locator of confirm button

packages/wallets/src/metamask/metamask.page.ts
- update MM addNetwork function
=> MM fix after app upgrade

wallets-testing/test/widgets/ethereum.spec.ts
=> Unskip Trust wallet

packages/wallets/src/metamask/metamask.page.ts, packages/widgets/src/ethereum/ethereum.page.ts
- try another way to close "MM News" modals
=> Another way to close the News' modals

packages/wallets/src/okx/okx.page.ts, wallets-testing/test/widgets/ethereum.spec.ts
=> fix okx new release

packages/wallets/src/metamask/metamask.page.ts, packages/wallets/src/wallet.page.ts
- created function for changing wallet address
=> change wallet address

package.json, packages/wallets/src/metamask/metamask.page.ts
- There is was issue when we try changeNetowork() to network that already selected and there is was 2 locators by geyByText(). Fixed by more direct locator inside netoworks preview
=> fix: changeNetwork() for MM

packages/wallets/src/coinbase/coinbase.page.ts, packages/wallets/src/okx/okx.page.ts, wallets-testing/package.json
fix: reworked initial awaiting OKX wallet
=> Fix OKX wallet initialization

packages/wallets/src/okx/okx.page.ts
- fix okx password inputs locators
=> fix: okx password inputs

packages/wallets/src/metamask/metamask.page.ts
=> fix: getTokenBalance

wallets-testing/browser/browser.service.ts, wallets-testing/playwright.config.ts
fix: fixed screenshot on the test fail
=> fixed screenshot on the test fail

packages/wallets/src/metamask/metamask.page.ts, packages/wallets/src/wallet.page.ts
feat: added the cancelSignTx function
fix: fixed locator transaction signing
=> Fix the transaction signing

package.json, packages/wallets/src/metamask/metamask.page.ts, packages/wallets/src/metamask/pages/walletOperations.page.ts
- fixed the tx modal locators after the metamask extensions updated
=> Fix mm tx locators after the extension update to 12.3.0

packages/wallets/src/metamask/metamask.page.ts, packages/wallets/src/metamask/pages/walletOperations.page.ts, packages/wallets/src/wallet.page.ts
fix: rework the cancel and confirm transaction function
=> Update cancel and confirm transaction function after MM version updated

package.json, packages/wallets/src/metamask/metamask.constants.ts, packages/wallets/src/metamask/metamask.page.ts
- set correct CONNECT_BUTTON_NAME to be ok with  .getByText(walletName, `{ exact: true }`);
=> fix: set MM correct name

packages/widgets/src/ethereum/ethereum.page.ts
- fix locator for stakePage input() for `widget` package
=> fix: locator for stakePage input()

package.json, packages/wallets/src/metamask/metamask.page.ts, packages/wallets/src/metamask/pages/elements/header.element.ts, packages/wallets/src/metamask/pages/elements/networkSetting.element.ts, packages/wallets/src/metamask/pages/settings.page.ts, packages/wallets/src/wallet.page.ts, packages/widgets/src/ethereum/ethereum.constants.ts
Update network settings after release https://github.com/MetaMask/metamask-extension/releases/tag/v12.5.0
=> fix: update network settings

packages/wallets/src/metamask/metamask.page.ts
- trigger publish since it triggered
=> feat: trigger deploy

packages/wallets/src/metamask/metamask.page.ts, packages/wallets/src/okx/okx.page.ts
chore: use the toLowerCase() of the wallet address for OKX and MM wal…lets
=> Use the toLowerCase() of the wallet address

packages/wallets/src/metamask/metamask.page.ts, packages/wallets/src/okx/okx.page.ts
feat: return lower case address
=> Return lower case address

packages/wallets/src/ctrl/pages/onboarding.page.ts
=> Update "Ctrl" wallet onboarding flow.

package.json, packages/discord-reporter/README.md, packages/discord-reporter/src/index.ts
Fixed issue with failed report
=> fix: initialize report

package.json
- fix alpha publish since missed to unmock [here](https://github.com/lidofinance/wallets-testing-modules/pull/219)
=> fix: unmock alpha publish

packages/wallets/src/okx/okx.page.ts, packages/wallets/src/okx/pages/onboarding.page.ts
- fixed OKX wallet setup process (OKX updated by Feb. 20)
=> Fix OKX wallet setup

packages/wallets/src/EOA/trustwallet/pages/onboarding.page.ts
-  fixed setup process after trust wallet updated
=> Fix trust wallet setup process

packages/wallets/src/EOA/coin98/coin98.constants.ts, packages/wallets/src/EOA/coin98/coin98.page.ts
- update `firstTimeSetup()` after coin98 update
=> fix: coin98 'firstTimeSetup()' after update

packages/discord-reporter/src/index.ts, packages/wallets/src/EOA/ctrl/pages/login.page.ts, packages/wallets/src/EOA/ctrl/pages/onboarding.page.ts, packages/wallets/src/EOA/metamask/pages/elements/networkList.element.ts, packages/wallets/src/EOA/metamask/pages/onboarding.page.ts, packages/wallets/src/EOA/okx/okx.page.ts, packages/wallets/src/EOA/okx/pages/login.page.ts, packages/wallets/src/EOA/okx/pages/networkList.page.ts, packages/wallets/src/EOA/okx/pages/walletOperations.page.ts, packages/wallets/src/EOA/trustwallet/pages/login.page.ts, packages/wallets/src/EOA/trustwallet/pages/walletOperations.page.ts, packages/wallets/src/EOA/trustwallet/trustWallet.page.ts, packages/wallets/src/WC/safe/pages/home.page.ts, packages/wallets/src/WC/safe/pages/setup.page.ts, packages/wallets/src/WC/safe/safe.page.ts, wallets-testing/config/env.validation.ts
- removed all `console.log()`, `console.error()`
- used `@nestjs/common` logger
=> feat: change all console.log to @nestjs/ConsoleLogger

packages/wallets/src/wallets.constants.ts
- added `Hoodi` network config (❕ _need to update rpc and scan urls_)
- added `Unichain` network config
- added `Unichain Sepolia` network config
- added `Lisk` network config
=> Add Hoodi and other network config

packages/wallets/src/EOA/metamask/pages/elements/networkList.element.ts
- fix `openModalNetworkEdit` locator for latest MM version && LATEST_STABLE_DOWNLOAD_LINK
=> fix: openModalNetwork locator using different mm version

packages/wallets/src/wallets.constants.ts
=> fix: update optimism rpc

packages/wallets/src/EOA/metamask/pages/elements/accountMenu.element.ts
- fix MM "Import private key" locator after MM update
=> fix: MM "Import private key" locator

package.json, packages/wallets/src/EOA/metamask/pages/elements/networkList.element.ts
=> fix: edit defaultNetwork with rpc

packages/wallets/src/EOA/trustwallet/pages/onboarding.page.ts, packages/wallets/src/EOA/trustwallet/trustWallet.page.ts
Notes:
- fixed trust wallet after updated
=> fix TrustWallet after updated

packages/wallets/src/EOA/metamask/helper.ts, packages/wallets/src/wallets.constants.ts
- add `AVAX` network && add `AVAX` to MM polular networks
=> feat: add AVAX network && add AVAX to MM popular

packages/wallets/src/EOA/coin98/coin98.page.ts
fix: fixed wallet installation
=> Fix Coin98 installation

packages/wallets/src/EOA/trustwallet/pages/onboarding.page.ts
- update trust-w onboarding locator
=> fix: trust-w onboarding locator

packages/wallets/src/metamask/pages/onboarding.page.ts
- update onboarding MM
Currently fails https://github.com/lidofinance/wallets-testing-modules/actions/runs/16573375224
=> fix: mm onboarding on final waiting

packages/wallets/src/metamask/metamask-latest/pages/login.page.ts, packages/wallets/src/safe/pages/setup.page.ts, packages/wallets/src/safe/pages/transaction.page.ts, packages/wallets/src/safe/safeIframe.page.ts, wallets-testing/config/config.ethereumWidget.ts, wallets-testing/pages/iframeWidget.page.ts, wallets-testing/pages/widget.page.ts, wallets-testing/services/service.widget.ts, wallets-testing/test/widgets/iframeWidget.spec.ts, wallets-testing/utils/helpers.ts
feat: create tests of wrap, unwrap, withdraw transactions
=> Iframe transactions
