lidofinance/wallets-testing-modules

- packages/wallets/src/exodus/exodus.page.ts
- packages/wallets/src/phantom/phantom.page.ts
- packages/wallets/src/taho/taho.constants.ts
Taho
- Set new connect button name to "Taho:
Exodus
- Exodus has excluded password init for setup(). 
- Added timeout for wallet connect confirmation since it`s failed sometimes due to fast click on pop-up(IMO)
> Fix some wallet problems

- packages/wallets/src/taho/taho.page.ts
Taho added some metamask conflict  pop-up(but in test there is no metamask installed)
> fix taho-metamask pop-up

- packages/wallets/src/bitKeep/bitKeep.constants.ts
- packages/wallets/src/bitKeep/bitKeep.page.ts
- packages/wallets/src/bitKeep/index.ts
- packages/wallets/src/index.ts
- wallets-testing/browser/browser.constants.ts
- wallets-testing/browser/browser.context.service.ts
- wallets-testing/browser/browser.service.ts
- wallets-testing/test/widgets/ethereum.spec.ts
- Added BitKeep wallet connect test to ETH
- Added logic to detect extensionId in browser.context.serivece.ts -> setExtensionVars() since the setExtensionVars() cannot recognize the manifest version since the bitKeep manifest has a persistence: false proprety which mean that extension doesn't leave in background until manual call.
> BitKeep wallet init

- packages/wallets/src/bitKeep/bitKeep.page.ts
- packages/wallets/src/coin98/coin98.page.ts
- wallets-testing/browser/browser.service.ts
- updated coin98 wallet connection test
- updated bitKeep wallet connection test
- added closePage() in browserService.setup() to avoid double opened wallet setup tabs due to coin98 displayed "Multiple Windows are detected, close another window before continuing!" conflict if 2 extension tabs opened
> Wallets fixes

- packages/wallets/src/metamask/metamask.page.ts
- packages/wallets/src/wallet.page.ts
- packages/widgets/src/ethereum/ethereum.page.ts
- [feat: add aggerssive gas cost option for confirmTx()] - ability to set aggressive gas coast to speed up tx time and don' fail on waitTimeout for page
- [fix: make assertReceiptAddress() reusable for any network] - set more abstract locators for assertReceiptAddress() to use it in any network. For now was that was parsed constant for ETH stake contract in MM as 'text=Liquid staked Ether 2.0',but it`s not worked for example for Goerli network since it's not parsed as a Lido stake contract via MM
> Update for MM

- packages/wallets/src/okx/okx.page.ts
- wallets-testing/test/widgets/ethereum.spec.ts
- wallets-testing/test/widgets/polygon.spec.ts
- fix OKX test since at the last seed word input there is was multi-select of wording 
- add bitGet,taho,trust, phantom wallets connect tests to polygon
- enable xdefi since looks like it's fixed indirectly
- add phantom connect to ETH
> Wallets update

- packages/wallets/src/metamask/metamask.page.ts
- packages/wallets/src/wallet.page.ts
fix token balance by token name since need to find by name 'stETH'/'ETH' but in row it's looks like '0.1233 ETH' && '10 stETH'. If find by page.getByTestId('multichain-token-list-item-value').getByText('stETH'/'ETH') the inpu of  'ETH' will always resolve 2 elements since 'ETH' contain 'st[ETH]'. Option {exact:true} not worked because there is string value of token - "[10] stETH"
> fix MM getTokenBalance()

- packages/wallets/src/metamask/metamask.page.ts
- try to avoid "attempting click action  waiting for element to be visible, enabled and stable" by ```
{
force: true,
});
```
```
waiting for locator('data-testid=onboarding-terms-checkbox')
locator resolved to <input readonly type="checkbox" id="onboarding__terms-c…/>
attempting click action  waiting for element to be visible, enabled and stable
```
Some times it's happens with checkbox locators
> fix: try force click on MM onboarding-terms-checkbox

- packages/wallets/src/metamask/metamask.page.ts
- for some reason, after click on "edit-gas-fee-icon' mouse is still on this position that lead to hover on tooltip which overlaps the "aggressive" button
> fix: mouse move avoid unusable hover

- packages/extensions/src/extension.service.ts
- reuse downloaded extension to prevent multiply downloads. Extension stores in extensions/extension directory in modules with temp directory.
Problems:
- Once extension is downloaded there is a check for isExtensionDirEmpty() which leads to outdated extension on distance for local development.
- Otherwise for e2e tests it's works since for each run there is only 1 download.
> chore: reuse extension during run

- wallets-testing/test/widgets/ethereum.spec.ts
Skip Trust wallet on eth widget while it's not resolved from Trust wallet side
> fix: skip Trust for Eth widget

- packages/wallets/src/okx/okx.page.ts
- Fix okx firstTimeSetup. Okx added one more label with "Import wallet" as the tittle and there is was conflicts with 2 texts. Locators isn't so good since there is only divs without good locators
> fix: okx firstTimeSetup()

- package.json
- packages/wallets/src/metamask/metamask.page.ts
- Added extra wait for changeWalletAddress since if test very fast browser context doesn't have enough time to save switched address to context before test ends
> extra wait for changeWalletAddress()

- package.json
- packages/wallets/src/metamask/metamask.page.ts
Since shared browser_context saves data about ongoing but not confirmed transaction and passes it to new opened contex there is `jectAllTxInQueue()` in navigation() MM. It should reject all tx's while.
rejectAllTxInQueue- add `rejectAllTxInQueue()` into navigation() function to reject queue TX from prev tx context fails
> reject tx 

- wallets-testing/test/widgets/polygon.spec.ts
- skip coin98 connection for polygon widget since there is issues with connection on polygon widget side
> fix: skip coin98 for polygon widget

- package.json
- packages/wallets/package.json
- packages/wallets/src/metamask/metamask.page.ts
- packages/wallets/src/metamask/pages/elements/popover.element.ts
- packages/wallets/src/metamask/pages/walletOperations.page.ts
- yarn.lock
- updated mm `connectWallet()` flow 
- updated locator/flow  for `confirmTransactionOfTokenApproval()`
- added viem for `wallets` package to get  `getCheckSum` address 0x107209ce35ab1a0b3a22593ba85382817f471cd -> 0x107209CE35Ab1a0B3a22593ba85382817F471CDe since MM shows only in lower case. Bumped ts version to resolve conflicts with viem.
- MM provide checkSummed address but only with "Copy to clipboard" button but for wallets setup there is no option to  get from clippoard since [metamask/lavamoat](https://github.com/LavaMoat/LavaMoat/pull/360) blocked it.
> fix: mm connect flow

- packages/wallets/src/metamask/metamask.page.ts
- packages/wallets/src/metamask/pages/settings.page.ts
- Check the network toggle state every setup, because if the test run fails before toggle state is changed, the next test runs without that setting
> Check the network toggle state

- .github/workflows/test.yml
- decrease the ubuntu version for CI to 22.04
- the new ubuntu version - 24 - throw the error in the test run 
- failed test run - https://github.com/lidofinance/wallets-testing-modules/actions/runs/12651166415/job/35251197173)
> Change Ubuntu version for CI tests run

- package.json
- packages/wallets/src/bitget/bitgetPage.ts
- packages/wallets/src/coin98/coin98.page.ts
- packages/wallets/src/coinbase/coinbase.page.ts
- packages/wallets/src/exodus/exodus.page.ts
- packages/wallets/src/metamask/metamask.page.ts
- packages/wallets/src/metamask/pages/elements/networkList.element.ts
- packages/wallets/src/metamask/pages/elements/networkSetting.element.ts
- packages/wallets/src/metamask/pages/settings.page.ts
- packages/wallets/src/metamask/pages/walletOperations.page.ts
- packages/wallets/src/okx/okx.page.ts
- packages/wallets/src/okx/pages/networkList.page.ts
- packages/wallets/src/trustwallet/trustWalletPage.ts
- packages/wallets/src/wallet.page.ts
- packages/wallets/src/wallets.constants.ts
- wallets-testing/browser/browser.service.ts
- created `NetworkConfig` for use in the wallet functions
- fixed some oldest moments
- add networks `Mainnet`/`Testnet`
> Improve network config

- package.json
- packages/extensions/src/extension.service.ts
- packages/wallets/src/metamask/metamask.constants.ts
- packages/wallets/src/metamask/metamask.page.ts
- packages/wallets/src/metamask/pages/settings.page.ts
- packages/wallets/src/okx/okx.page.ts
- packages/wallets/src/wallet.page.ts
- packages/wallets/src/wallets.constants.ts
- wallets-testing/browser/browser.service.ts
- add ability to pass github link to download concrete version of any wallet.
- Right now `LATEST_STABLE_DOWNLOAD_LINK` stored only for `Metamask`. At this point means that all extensions would be download latest from chrome store,but metamask download from `LATEST_STABLE_DOWNLOAD_LINK`
- downloadUrl - optional param.
1) Main call
```
walletConfig.EXTENSION_PATH =
await this.extensionService.getExtensionDirFromId(
commonWalletConfig.STORE_EXTENSION_ID,
commonWalletConfig.LATEST_STABLE_DOWNLOAD_LINK,
);
```
2) downloadConcrete version using github store
```
process.env.EXTENSION_PATH =
await new ExtensionService().getExtensionDirFromId(
walletConfig.STORE_EXTENSION_ID,
// optional param with concrete version via `LATEST_STABLE_DOWNLOAD_LINK`
walletConfig.LATEST_STABLE_DOWNLOAD_LINK,
);
); …
```
> fix: add param for `latestStableDownloadUrl` to download extension

- packages/discord-reporter/src/index.ts
- update report msg format to Discord
- added `customTitle` and `customDescription` params to `discordReporter`
- example on the img below
- first msg - without `customTitle` and `customDescription`
- other msgs - with `customTitle` and `customDescription`
- How to Use?  See here -> https://github.com/lidofinance/lido-autotests/pull/242
_p.s. incorrect GitHub link because the local run_
> change the Discord report msg format

- package.json
- packages/browser-service/src/browser.context.service.ts
- packages/wallets/src/EOA/metamask/pages/elements/networkList.element.ts
🎭 Since we launch the browser context separately, the Playwright config wasn’t applied — meaning the reducedMotion setting wasn’t passed to the browser either. As a result, animations continued to run 😕
🛠️ I’ve added support for passing this option directly into the browser context, so now animations can be properly disabled when needed ✅
> feat: add reducedMotion options to BrowserContext

- package.json
- packages/browser-service/package.json
- packages/discord-reporter/package.json
- packages/extensions/package.json
- packages/nodes/package.json
- packages/pg-reporter/package.json
- packages/wallets/package.json
📦 Moved Playwright to peerDependencies
This update improves version consistency across our repositories by:
- 🔄 Moving Playwright from devDependencies to peerDependencies
- 🧩 Fixing version conflicts when trying to upgrade Playwright in main repos
- 🚫 Preventing duplicate installations that used to cause runtime errors
Thanks to this change, Playwright will now be managed by the main repository, ensuring smoother upgrades and better compatibility ✅
> feat: move pw to peer deps

- packages/browser-service/src/browser.service.ts
- Made the nodeConfig parameter optional, since not all projects require using the fork.
> feat: nodeConfig is optional

- package.json
- packages/pg-reporter/README.md
- packages/pg-reporter/package.json
- packages/pg-reporter/src/grafanaClient.ts
- packages/pg-reporter/src/index.ts
- packages/pg-reporter/src/reportRuntime.ts
- packages/pg-reporter/src/types.ts
- packages/pg-reporter/src/utils.ts
- yarn.lock
Changes Introduced
•	Grafana annotations: added the ability to publish annotations via the Grafana API, so it’s visible when a particular run was completed.
•	Label update: renamed projectName → appName to identify our applications as apps instead of projects.
•	Metrics adaptation for Landing: adjusted metrics to align with the Landing system, where the concept of “projects” is used to distinguish between browser types.
•	Scheduled runs only: enabled publishing metrics only for tests triggered automatically on schedule. Manual runs will no longer be included.
•	Cleanup: removed unused metrics.
> feat: implement PgReporter class with metrics tracking and reporting functionality
